name: Webtop

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Download ngrok
        run: |
          cd ~
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null &&
              echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list &&
              sudo apt update && sudo apt install ngrok
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      
      - name: Run install
        run: |
          docker run -d \
            --name=webtop \
            --privileged `#optional` \
            -e PUID=1000 \
            -e PGID=1000 \
            -e TZ=Asia/Singapore \
            -p 3000:3000 \
            --shm-size="4gb" `#optional` \
            --restart unless-stopped \
            lscr.io/linuxserver/webtop:ubuntu-kde
          ngrok http -region ap --log=stdout 3000
